### ISSUE TITLE
active?

### ISSUE THREAD

**Issue by mrc4tt** [Blackhaze36/SteamBot#1]
Hello @Blackhaze36 

Are you still active? =)
Are you planned to update it to the newest version?

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 55, in on_message
    await client.send_message(message.channel, x)
AttributeError: 'Client' object has no attribute 'send_message'
```
```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/discord/client.py", line 312, in _run_event
    await coro(*args, **kwargs)
  File "main.py", line 55, in on_message
    await channel.send(message.channel, x)
NameError: name 'channel' is not defined
```

**Comment by mrc4tt** [comment]
Hey. @Blackhaze36 are you active on GitHub? =)

**Comment by mrc4tt** [comment]
I think this is repo is dead. =)
